//@ sourceMappingURL=script.map
// Generated by CoffeeScript 1.6.1
(function() {

  (function() {
    $('.cont').mousedown(function() {
      return $('.up-arrow').css("borderColor", "blue transparent");
    });
    return $('.cont').mouseup(function() {
      return $('.up-arrow').css("borderColor", "#A2A2A2 transparent");
    });
  })();

}).call(this);
